CREATE TABLE test3 (
value1 STRING )
ClUSTERED BY (value1) INTO 1 BUCKETS
STORED AS ORC;

CREATE TABLE ex_table (
value1 STRING,
value2 STRING,
value3 STRING )
ClUSTERED BY (value1) INTO 1 BUCKETS
STORED AS ORC;